name: quast
description: Quality Assessment Tool for Genome Assemblies
keywords:
  - quast
  - assembly
  - quality
tools:
  - quast:
      description: |
        QUAST calculates quality metrics for genome assemblies
      homepage: http://bioinf.spbau.ru/quast
      doi:
input:
  - consensus:
      type: file
      description: |
        Fasta file containing the assembly of interest
  - fasta:
      type: file
      description: |
        The genome assembly to be evaluated. Has to contain at least a non-empty string dummy value.

output:
  - quast:
      type: directory
      description: Directory containing complete quast report
      pattern: "{prefix}.lineage_report.csv"
  - report:

  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@drpatelh"
  - "@kevinmenden"
